from typing import List, Dict, Any


class DocumentationAgent:
    """Agent 6 - Documentation Agent: Produces data lineage diagrams, transformation summaries, and migration docs."""

    def generate_documentation(self, source_file: str, steps: List[Dict[str, Any]]) -> str:
        doc = [
            f"# 📄 Data Migration & Lineage Documentation",
            f"**Source Project:** `{source_file}`",
            f"**Generated by:** SAS to PySpark Multi-Agent System",
            "",
            "---",
            "",
            "## 🗺️ Data Lineage Diagram",
            "```",
        ]

        for i, step in enumerate(steps, 1):
            inputs = ", ".join(step.get("inputs", [])) or "None/Source"
            outputs = ", ".join(step.get("outputs", [])) or "Temp/Target"
            name = step.get("name", f"Step_{i}")
            doc.append(f"[{inputs}] ──► ({name}: {step.get('block_type')}) ──► [{outputs}]")

        doc.extend([
            "```",
            "",
            "---",
            "",
            "## 📝 Transformation Steps Summary",
            ""
        ])

        for i, step in enumerate(steps, 1):
            doc.append(f"### Step {i}: {step.get('name')}")
            doc.append(f"- **Block Type:** `{step.get('block_type')}`")
            doc.append(f"- **Confidence Score:** `{int(step.get('confidence_score', 1.0) * 100)}%`")

            notes = step.get("notes", [])
            if notes:
                doc.append("- **Notes:** " + ", ".join(notes))

            warnings = step.get("warnings", [])
            if warnings:
                doc.append("- **Warnings:** " + "; ".join(warnings))

            opts = step.get("optimizations", [])
            if opts:
                doc.append("- **Optimizations:** " + "; ".join(opts))

            doc.append("")

        doc.extend([
            "---",
            "",
            "## ⚠️ Migration Assumptions & Unsupported Features",
            "- **Spark Compatibility:** PySpark 3.x / 4.x",
            "- **Date Handling:** SAS dates are converted to PySpark `DateType`.",
            "- **Null Values:** SAS missing numeric values (`.`) map to PySpark `null` / `None`.",
            "- **ODS Reporting:** Desktop ODS HTML/ActiveX graphic output statements (`PROC SGPLOT`, `PROC GCHART`) require BI reporting dashboard migration."
        ])

        return "\n".join(doc)
